CLEAN:
  n_timesteps: 10000000   # 1e7
  policy: 'LnMlpPolicy'
  verbose: 1
  gamma: 0.99
  noise_type: 'None'
  nb_eval_steps: 100
  nb_rollout_steps: 100
  nb_train_steps: 50
  buffer_size:  50000
  batch_size: 128
  actor_lr: 0.0001        # 1e-4
  critic_lr: 0.001        # 1e-3

TUNED:
  n_timesteps: 10000000   # 1e7
  policy: 'LnMlpPolicy'
  verbose: 1
  gamma: 0.99
  noise_type: 'None'
  nb_eval_steps: 2500
  nb_rollout_steps: 2500
  nb_train_steps: 1500
  buffer_size:  2000000   # 2e6
  batch_size: 32
  actor_lr: 0.001         # 1e-3
  critic_lr: 0.001        # 1e-3

NOISE:
  n_timesteps: 10000000   # 1e7
  policy: 'LnMlpPolicy'
  verbose: 1
  gamma: 0.99
  noise_type: 'ornstein-uhlenbeck'
  nb_eval_steps: 2500
  nb_rollout_steps: 2500
  nb_train_steps: 1500
  buffer_size:  2000000   # 2e6
  batch_size: 32
  actor_lr: 0.001         # 1e-3
  critic_lr: 0.001        # 1e-3