CLEAN:
  n_timesteps: 10000000   # 1e7
  policy: 'MlpPolicy'
  verbose: 1
  gamma: 0.99
  learning_starts: 100
  learning_rate: 0.0003
  noise_type: 'None'
  buffer_size:  50000
  batch_size: 128
  gradient_steps: 100
  train_freq: 100

TUNED:
  n_timesteps: 10000000   # 1e7
  policy: 'MlpPolicy'
  verbose: 1
  gamma: 0.99
  learning_starts: 25000
  learning_rate: 0.001
  noise_type: 'None'
  buffer_size:  1000000   # 1e6
  batch_size: 100
  gradient_steps: 2000
  train_freq: 2000

NOISE:
  n_timesteps: 10000000   # 1e7
  policy: 'MlpPolicy'
  verbose: 1
  gamma: 0.99
  learning_starts: 25000
  learning_rate: 0.001
  noise_type: 'ornstein-uhlenbeck'
  buffer_size:  1000000   # 1e6
  batch_size: 100
  gradient_steps: 2000
  train_freq: 2000

